name: EASeJ Tools beta Issue Report
description: Provide feedback about EASeJ Tools beta. It can be a bug you have found or an improvement you would like to see.
title: "[EASeJ Tools beta]: "
body:
  - type: markdown
    attributes:
      value: | 
        This template is specifically designed to collect feedback regarding the beta release of EASeJ Tools. Therefore, we request that you only report issues or experiences related to the beta release.

        Thank you for taking the time to share your feedback with us, we truly appreciate your input! 
  - type: textarea
    id: what-happened
    attributes:
      label: Can you explain what occurred?
      description: Tell us what happened and the sequence of steps you followed.
      placeholder: Steps to reproduce the behavior
      value: "1. Go to... \n2. Click on... \n3. Scroll down to... \n4. See the error/message"
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: Describe what you expected to happen.
      description: Tell us what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
      value: "I expected to see..."
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Did you try restarting Visual Studio Code, re-logging in, or using any other workaround? If so, did it help?
      placeholder: Tell us if you tried any workaround and what effect it had.
      value: "After restarting Visual Studio Code..."
    validations:
      required: false
  - type: dropdown
    id: OS
    attributes:
      label: Operating system
      description: Which operating system(s) are you using to run Visual Studio Code?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Visual Studio Code Version
      description: What version of Visual Studio Code are you using?
      placeholder: ex. version 1.101.2
    validations:
      required: false