name: Issue Report
description: Include feedback about EASeJ Tools Beta. It can be a bug you have found or an improvement you would like to see.
title: "[Issue]: "
labels: ["bug", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your feedback with us!
  - type: textarea
    id: what-happened
    attributes:
      label: Can you explain what occurred?
      description: Tell us what happened and the sequence of steps you followed.
      placeholder: Steps to reproduce the behavior
      value: "Go to... Click on... Scroll down to... See the error/message"
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: Describe what you expected to happen.
      description: Tell us what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
      value: "I expected to see..."
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Did you try restarting Visual Studio Code, re-logging in, or using any other workaround? If so, did it help?
      placeholder: Tell us if you tried any workaround and what effect it had.
      value: "After restarting Visual Studio Code..."
    validations:
      required: false
  - type: dropdown
    id: OS
    attributes:
      label: Operating system
      description: Which operating system(s) are you using to run Visual Studio Code?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Visual Studio Code Version
      description: What version of Visual Studio Code are you using?
      placeholder: ex. version 1.101.2
    validations:
      required: false